core: Better communicate errors to the CLI
- Add backtrace to fatal errors to help diagnosing bug reports (Pfff).
- Report rule evaluation errors instead of "silently" logging them.

Helps #3547

test plan:

    % cat fatal.py
    def foo():
    return 1
    }
    % semgrep -l py -e 'x' fatal.py
    running 1 rules...
    semgrep-core reported a fatal error:
    -----
    Fatal Error: (Failure "Lexer_python.top_mode: empty stack")
    Raised at Parse_target.run in file "src/parsing/Parse_target.ml", line 176, characters 17-26
    ...
    -----
    Please file a bug report at https://github.com/returntocorp/semgrep/issues/new/choose
    ...

    % cat warn.yaml
    rules:
    - id: test
      languages: [python]
      patterns:
      - pattern: $X
      - metavariable-pattern:
          metavariable: $Y
          pattern: x
      message: Test
      severity: ERROR
    % cat warn.py
    x
    % semgrep -c warn.yaml -v warn.py
    ...
    semgrep-core reported a matching error
    --> matching internal error: rule test: metavariable-pattern failed because $Y it not in scope, please check your rule
    ...